### ISSUE TITLE
ASERT name already taken?

### ISSUE THREAD

**Issue by mattmc3** [AlternateKeyboard/ASERT#1]
This ASERT layout name seems to be used in other similar layouts (which admittedly you acknowledge a few of in your readme):
- https://github.com/joaquinmartinezgc/ASERT (5 years ago)
- https://github.com/czipperz/asert (7 years ago)

You use an NYJ loop, and have a more robust justification - but given that yours is slightly different, have you considered distinguishing it with a (slightly) different name (ASERT2, ASERT-NYJ, etc)? Similar to how Colemak and Colemak-DH share the same origin, but are actually different layouts. It might make it easier to search for this variant or distinguish it in comparisons. 

Just a question - not necessarily an imperative. Since those other ASERT layouts are pretty low popularity and low activity, perhaps instead the goal is for this to be the new canonical ASERT?

**Comment by AlternateKeyboard** [comment]
After more work I recommend Norman instead of this for something easy to learn. See reddit.com/r/norman.

Or my other layout Middlemak https://github.com/KeyboardLayout2
